/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package primastrans;

import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author R
 */
public class frmSupplier extends javax.swing.JFrame {

    /**
     * Creates new form frmSupplier
     */
    public frmSupplier() {
        initComponents();
        this.setLocationRelativeTo(null);
        load_table();
        kosong();
        textboxOff();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnBaru1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnHapus1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIDSupp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTempatBongkar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        btnBatal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtKas = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtKasPrimas = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtKord = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        txtStockpile = new javax.swing.JTextField();
        txtKdDO = new javax.swing.JTextField();
        txtDO = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTab = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(184, 92, 17));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("DATA SUPPLIER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 780, 230));

        jPanel7.setBackground(new java.awt.Color(184, 92, 17));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel7.setToolTipText("");

        btnBaru1.setBackground(new java.awt.Color(204, 204, 204));
        btnBaru1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnBaru1.setForeground(new java.awt.Color(204, 204, 204));
        btnBaru1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBaru1.setText("Baru");
        btnBaru1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBaru1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBaru1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBaru1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        jPanel5.setBackground(new java.awt.Color(184, 92, 17));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel5.setToolTipText("");

        btnHapus1.setBackground(new java.awt.Color(204, 204, 204));
        btnHapus1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnHapus1.setForeground(new java.awt.Color(204, 204, 204));
        btnHapus1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHapus1.setText("Hapus");
        btnHapus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapus1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        jPanel2.setBackground(new java.awt.Color(242, 233, 242));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Kode DO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        txtIDSupp.setBackground(new java.awt.Color(242, 233, 242));
        txtIDSupp.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtIDSupp.setForeground(new java.awt.Color(102, 102, 102));
        txtIDSupp.setText("ID Supplier");
        txtIDSupp.setBorder(null);
        jPanel2.add(txtIDSupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 170, 30));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("DO");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, -1, -1));

        txtTempatBongkar.setBackground(new java.awt.Color(242, 233, 242));
        txtTempatBongkar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtTempatBongkar.setForeground(new java.awt.Color(102, 102, 102));
        txtTempatBongkar.setText("Tempat Bongkar");
        txtTempatBongkar.setBorder(null);
        txtTempatBongkar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTempatBongkarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTempatBongkarFocusLost(evt);
            }
        });
        jPanel2.add(txtTempatBongkar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 170, 30));

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Stockpile");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Tempat Bongkar");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator5.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 170, 10));

        jSeparator6.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator6.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 170, 10));

        jSeparator7.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator7.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 170, 10));

        jSeparator8.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator8.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 170, 10));

        btnBatal.setBackground(new java.awt.Color(102, 102, 102));
        btnBatal.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(102, 102, 102));
        btnBatal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBatal.setText("Batal");
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
        });
        jPanel2.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 102, 38));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("×");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, 20));

        jPanel4.setBackground(new java.awt.Color(242, 233, 242));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel4.setToolTipText("");

        btnSimpan.setBackground(new java.awt.Color(102, 102, 102));
        btnSimpan.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(102, 102, 102));
        btnSimpan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSimpan.setText("Simpan");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, -1, 40));

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Kas");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        txtKas.setBackground(new java.awt.Color(242, 233, 242));
        txtKas.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtKas.setForeground(new java.awt.Color(102, 102, 102));
        txtKas.setText("0");
        txtKas.setBorder(null);
        txtKas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtKasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKasFocusLost(evt);
            }
        });
        jPanel2.add(txtKas, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, 170, 30));

        jSeparator9.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator9.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 170, 10));

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Kas Primas");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));

        txtKasPrimas.setBackground(new java.awt.Color(242, 233, 242));
        txtKasPrimas.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtKasPrimas.setForeground(new java.awt.Color(102, 102, 102));
        txtKasPrimas.setText("0");
        txtKasPrimas.setBorder(null);
        txtKasPrimas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtKasPrimasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKasPrimasFocusLost(evt);
            }
        });
        jPanel2.add(txtKasPrimas, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 170, 30));

        jSeparator10.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator10.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 170, 10));

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Koordinasi");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, -1, -1));

        txtKord.setBackground(new java.awt.Color(242, 233, 242));
        txtKord.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtKord.setForeground(new java.awt.Color(102, 102, 102));
        txtKord.setText("0");
        txtKord.setBorder(null);
        txtKord.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtKordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKordFocusLost(evt);
            }
        });
        jPanel2.add(txtKord, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 170, 30));

        jSeparator11.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator11.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 170, 10));

        jLabel16.setBackground(new java.awt.Color(102, 102, 102));
        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("ID Supllier");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        jSeparator18.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator18.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 170, 10));

        jLabel19.setBackground(new java.awt.Color(204, 204, 204));
        jLabel19.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("?");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, 20));

        txtStockpile.setBackground(new java.awt.Color(242, 233, 242));
        txtStockpile.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtStockpile.setForeground(new java.awt.Color(102, 102, 102));
        txtStockpile.setText("Stockpile");
        txtStockpile.setBorder(null);
        txtStockpile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtStockpileFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtStockpileFocusLost(evt);
            }
        });
        jPanel2.add(txtStockpile, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 170, 30));

        txtKdDO.setBackground(new java.awt.Color(242, 233, 242));
        txtKdDO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtKdDO.setForeground(new java.awt.Color(102, 102, 102));
        txtKdDO.setText("Kode DO");
        txtKdDO.setBorder(null);
        txtKdDO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtKdDOFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKdDOFocusLost(evt);
            }
        });
        jPanel2.add(txtKdDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 170, 30));

        txtDO.setBackground(new java.awt.Color(242, 233, 242));
        txtDO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtDO.setForeground(new java.awt.Color(102, 102, 102));
        txtDO.setText("Delivery Order");
        txtDO.setBorder(null);
        txtDO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDOFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDOFocusLost(evt);
            }
        });
        jPanel2.add(txtDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 170, 30));

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Tabungan");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, -1, -1));

        txtTab.setBackground(new java.awt.Color(242, 233, 242));
        txtTab.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtTab.setForeground(new java.awt.Color(102, 102, 102));
        txtTab.setText("0");
        txtTab.setBorder(null);
        txtTab.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTabFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTabFocusLost(evt);
            }
        });
        jPanel2.add(txtTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 170, 30));

        jSeparator12.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator12.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 170, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idSupp() {
        try {
            String sql = "select * from tb_supplier ORDER BY LENGTH(id_supplier) desc, id_supplier desc";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet rs=stm.executeQuery(sql);
            if (rs.next()) {
                String kd = rs.getString("id_supplier").substring(3);
                String AN = "" + (Integer.parseInt(kd) + 1);
                txtIDSupp.setText("SPL" + AN);
            } else {
                txtIDSupp.setText("SPL1");
            }

           }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
           }
    }
    
     private void textboxOn() {
        txtKdDO.setEditable(true);
        txtDO.setEditable(true);
        txtStockpile.setEditable(true);
        txtTempatBongkar.setEditable(true);
        txtKas.setEditable(true);
        txtKasPrimas.setEditable(true);
        txtKord.setEditable(true);
        txtTab.setEditable(true);
        jPanel4.setVisible(true);
        btnSimpan.setVisible(true);
        btnBatal.setVisible(true);
    }
    
    private void textboxOff() {
        txtIDSupp.setEnabled(false);
        txtKdDO.setEditable(false);
        txtDO.setEditable(false);
        txtStockpile.setEditable(false);
        txtTempatBongkar.setEditable(false);
        txtKas.setEditable(false);
        txtKasPrimas.setEditable(false);
        txtKord.setEditable(false);
        txtTab.setEditable(false);
        jPanel4.setVisible(false);
        btnSimpan.setVisible(false);
        btnBatal.setVisible(false);
    }
    
    private void kosong(){
        txtIDSupp.setText("ID Suplier");
        txtKdDO.setText("Kode DO");
        txtDO.setText("Delivery Order");
        txtStockpile.setText("Stockpile");
        txtTempatBongkar.setText("Tempat Bongkar");
        txtKas.setText("0");
        txtKasPrimas.setText("0");
        txtKord.setText("0");
        txtTab.setText("0");
    }
    
    private void load_table(){
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Supplier");
        model.addColumn("Kode DO");
        model.addColumn("DO");
        model.addColumn("Stock Pile");
        model.addColumn("Tempat Bongkar");
        model.addColumn("Kas");
        model.addColumn("Kas Primas");
        model.addColumn("Kord");
        model.addColumn("Tab");
        
        //menampilkan data database kedalam tabel
        try {
            String sql = "select * from tb_supplier ORDER BY LENGTH(id_supplier) asc, id_supplier asc";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8),res.getString(9)});
            }
            jTable1.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.rowAtPoint(evt.getPoint());
        String idsupp =jTable1.getValueAt(baris, 0).toString();
        txtIDSupp.setText(idsupp);
        String kddo=jTable1.getValueAt(baris, 1).toString();
        txtKdDO.setText(kddo);
        String deo=jTable1.getValueAt(baris, 2).toString();
        txtDO.setText(deo);
        String stockpile=jTable1.getValueAt(baris, 3).toString();
        txtStockpile.setText(stockpile);
        String nama=jTable1.getValueAt(baris, 4).toString();
        txtTempatBongkar.setText(nama);
        String nopol =jTable1.getValueAt(baris, 5).toString();
        txtKas.setText(nopol);
        String bayaran = jTable1.getValueAt(baris,6).toString();
        txtKasPrimas.setText(bayaran);
        String koordinasi=jTable1.getValueAt(baris, 7).toString();
        txtKord.setText(koordinasi);
        String tab=jTable1.getValueAt(baris, 7).toString();
        txtTab.setText(tab);
        textboxOn();
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnBaru1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBaru1MouseClicked
        // TODO add your handling code here:
        textboxOn();
        kosong();
        idSupp();
    }//GEN-LAST:event_btnBaru1MouseClicked

    private void btnHapus1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapus1MouseClicked
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Benarkah anda ingin menghapus data ini?", "Penghapusan Data", JOptionPane.YES_NO_OPTION);
        if (opsi == JOptionPane.YES_OPTION){
            try {
                String sql ="delete from tb_supplier_supir where id_supplier='"+txtIDSupp.getText()+"'";
                java.sql.Connection conn=(Connection)Config.configDB();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(this, "Data berhasil di hapus.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            load_table();
            kosong();
        }else{
            JOptionPane.showMessageDialog(null, "Data batal dihapus.");
        }
    }//GEN-LAST:event_btnHapus1MouseClicked

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        // TODO add your handling code here:
        textboxOff();
        kosong();
    }//GEN-LAST:event_btnBatalMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new mainMenu().setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        // TODO add your handling code here:
        try{
            String query = "select * from tb_supplier where id_supplier = '"+txtIDSupp.getText()+"'";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(query);
            if(res.next()){
                String sql ="UPDATE tb_supplier SET id_supplier = '"+txtIDSupp.getText()+"', kd_do = '"+txtKdDO.getText()+"', do = '"+txtDO.getText()+"',stockpile = '"+txtStockpile.getText()+"',tempat_bongkar = '"+txtTempatBongkar.getText()+"',kas = '"+txtKas.getText()+"',kas_primas = '"+txtKasPrimas.getText()+"',kord = '"+txtKord.getText()+"',tab = '"+txtTab.getText()+"' WHERE id_supplier = '"+txtIDSupp.getText()+"'";
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "data berhasil diedit");
            }else{
                String sql = "INSERT INTO tb_supplier VALUES ('"+txtIDSupp.getText()+"', '"+txtKdDO.getText()+"', '"+txtDO.getText()+"', '"+txtStockpile.getText()+"', '"+txtTempatBongkar.getText()+"', '"+txtKas.getText()+"', '"+txtKasPrimas.getText()+"', '"+txtKord.getText()+"', '"+txtTab.getText()+"')";
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Penyimpanan data berhasil");
            }
            load_table();
            textboxOff();
            kosong();
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void txtKasPrimasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKasPrimasFocusGained
        // TODO add your handling code here:
        if (txtKasPrimas.getText().equals("0")){
            txtKasPrimas.setText("");
        }
    }//GEN-LAST:event_txtKasPrimasFocusGained

    private void txtKasPrimasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKasPrimasFocusLost
        // TODO add your handling code here:
        if (txtKasPrimas.getText().equals("")){
            txtKasPrimas.setText("0");
        }

    }//GEN-LAST:event_txtKasPrimasFocusLost

    private void txtKordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKordFocusGained
        // TODO add your handling code here:
        if (txtKord.getText().equals("0")){
            txtKord.setText("");
        }
    }//GEN-LAST:event_txtKordFocusGained

    private void txtKordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKordFocusLost
        // TODO add your handling code here:
        if (txtKord.getText().equals("")){
            txtKord.setText("0");
        }
    }//GEN-LAST:event_txtKordFocusLost

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Form Supplier.\n - Mengisikan data: Klik 'Baru' lalu form akan tersedia untuk diisi.\n - Mengubah data: Piih data lalu klik pada tabel, data akan muncul di form untuk diubah.\n - Menghapus data: Piih data lalu klik pada tabel, lalu tekan tombol 'Hapus' data akan terhapus.");
    }//GEN-LAST:event_jLabel19MouseClicked

    private void txtTabFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTabFocusGained
        // TODO add your handling code here:
        if (txtTab.getText().equals("0")){
            txtTab.setText("");
        }
    }//GEN-LAST:event_txtTabFocusGained

    private void txtTabFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTabFocusLost
        // TODO add your handling code here:
        if (txtTab.getText().equals("")){
            txtTab.setText("0");
        }
    }//GEN-LAST:event_txtTabFocusLost
    int xy, xx;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void txtKdDOFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKdDOFocusGained
        // TODO add your handling code here:
        if (txtKdDO.getText().equals("Kode DO")){
            txtKdDO.setText("");
        }
    }//GEN-LAST:event_txtKdDOFocusGained

    private void txtDOFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDOFocusGained
        // TODO add your handling code here:
        if (txtDO.getText().equals("Delivery Order")){
            txtDO.setText("");
        }
    }//GEN-LAST:event_txtDOFocusGained

    private void txtStockpileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStockpileFocusGained
        // TODO add your handling code here:
        if (txtStockpile.getText().equals("Stockpile")){
            txtStockpile.setText("");
        }
    }//GEN-LAST:event_txtStockpileFocusGained

    private void txtTempatBongkarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTempatBongkarFocusGained
        // TODO add your handling code here:
        if (txtTempatBongkar.getText().equals("Tempat Bongkar")){
            txtTempatBongkar.setText("");
        }
    }//GEN-LAST:event_txtTempatBongkarFocusGained

    private void txtKasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKasFocusGained
        // TODO add your handling code here:
        if (txtKas.getText().equals("0")){
            txtKas.setText("");
        }
    }//GEN-LAST:event_txtKasFocusGained

    private void txtKdDOFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKdDOFocusLost
        // TODO add your handling code here:
        if (txtKdDO.getText().equals("")){
            txtKdDO.setText("Kode DO");
        }
    }//GEN-LAST:event_txtKdDOFocusLost

    private void txtDOFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDOFocusLost
        // TODO add your handling code here:
        if (txtDO.getText().equals("")){
            txtDO.setText("Delivery Order");
        }
    }//GEN-LAST:event_txtDOFocusLost

    private void txtStockpileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStockpileFocusLost
        // TODO add your handling code here:
        if (txtStockpile.getText().equals("")){
            txtStockpile.setText("Stockpile");
        }
    }//GEN-LAST:event_txtStockpileFocusLost

    private void txtTempatBongkarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTempatBongkarFocusLost
        // TODO add your handling code here:
        if (txtTempatBongkar.getText().equals("")){
            txtTempatBongkar.setText("Tempat Bongkar");
        }
    }//GEN-LAST:event_txtTempatBongkarFocusLost

    private void txtKasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKasFocusLost
        // TODO add your handling code here:
        if (txtKas.getText().equals("")){
            txtKas.setText("0");
        }
    }//GEN-LAST:event_txtKasFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBaru1;
    private javax.swing.JLabel btnBatal;
    private javax.swing.JLabel btnHapus1;
    private javax.swing.JLabel btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDO;
    private javax.swing.JTextField txtIDSupp;
    private javax.swing.JTextField txtKas;
    private javax.swing.JTextField txtKasPrimas;
    private javax.swing.JTextField txtKdDO;
    private javax.swing.JTextField txtKord;
    private javax.swing.JTextField txtStockpile;
    private javax.swing.JTextField txtTab;
    private javax.swing.JTextField txtTempatBongkar;
    // End of variables declaration//GEN-END:variables
}
