/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package primastrans;

/**
 *
 * @author R
 */
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

public class frmTransport extends javax.swing.JFrame {

    /**
     * Creates new form frmTransport
     */
    public frmTransport() {
        initComponents();
        this.setLocationRelativeTo(null);
        load_table();
        kosong();
        textboxOff();
        cmbID();
        cmbMobil();
        cmbNopol();
        cmbSupp();
        cmbKdDO();
        cmbSpr();
                
        
        cmbID.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                getSupir();
            }
        });
        
        cmbKdMobil.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                getMobil();
            }
        });
        
        cmbKdDO.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                getKdDO();
                jumlahtotal();
                susuttonase();
                cashinsupplier();
                cashinprimas();
            }
        });
    }

    private void notes(){
        try { 
            String sql = "select * from tb_supplier where kd_do = '"+cmbKdDO.getSelectedItem()+"'";
            java.sql.Connection conn=Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                long a = Integer.parseInt(res.getString("kas"));
                long b = Integer.parseInt(txtKas.getText());
                long c = a - b;
                txtNote.setText(Long.toString(c));
            }
        }catch (SQLException ex) {
            Logger.getLogger(frmTransport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    private void jumlahtotal(){
        long a = Long.parseLong(txtTonasePabrik.getText());
        long b = Long.parseLong(txtRP.getText());
        long c = a * b; 
        txtJumlahTotal.setText(Long.toString(c));
    }
    
    private void susuttonase(){
        long a = Long.parseLong(txtTonasePabrik.getText());
        long b = Long.parseLong(txtTonaseMuat.getText());
        long c = b - a; 
        txtSusutTonase.setText(Long.toString(c));
    }
    
    private void cashinsupplier(){
        long a = Long.parseLong(txtJumlahTotal.getText());
        long b = Long.parseLong(txtKas.getText());
        long c = a - b; 
        txtCashinSupplier.setText(Long.toString(c));
    }
    
    private void cashinprimas(){
        long a = Long.parseLong(txtCashinSupplier.getText());
        long b = Long.parseLong(txtKasPrimas.getText());
        long c = Long.parseLong(txtKord.getText());
        long d = Long.parseLong(txtTab.getText());
        long e = a - b - c - d; 
        txtCashinPrimas.setText(Long.toString(e));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnBaru1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnCetak = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnHapus1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnCetak1 = new javax.swing.JLabel();
        cmbSupp = new javax.swing.JComboBox<>();
        cmbMbl = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cmbDari = new com.toedter.calendar.JDateChooser();
        cmbSampai = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnCetak2 = new javax.swing.JLabel();
        cmbSopir = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        btnCetak3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtKdTransport = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        btnBatal = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtDO = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtTonasePabrik = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtKas = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        txtCashinSupplier = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtKasPrimas = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        txtKord = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        txtTab = new javax.swing.JTextField();
        jSeparator18 = new javax.swing.JSeparator();
        cmbID = new javax.swing.JComboBox<>();
        txtNama = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jSeparator19 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jSeparator20 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        txtRP = new javax.swing.JTextField();
        jSeparator22 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        txtJumlahTotal = new javax.swing.JTextField();
        jSeparator23 = new javax.swing.JSeparator();
        jLabel24 = new javax.swing.JLabel();
        txtCashinPrimas = new javax.swing.JTextField();
        jSeparator26 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        txtNoSJ = new javax.swing.JTextField();
        jSeparator27 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        txtSusutTonase = new javax.swing.JTextField();
        jSeparator28 = new javax.swing.JSeparator();
        jLabel27 = new javax.swing.JLabel();
        txtNote = new javax.swing.JTextField();
        jSeparator29 = new javax.swing.JSeparator();
        cmbKdMobil = new javax.swing.JComboBox<>();
        txtTempatBongkar = new javax.swing.JTextField();
        txtStockpile = new javax.swing.JTextField();
        txtTonaseMuat = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtNopol = new javax.swing.JTextField();
        jSeparator24 = new javax.swing.JSeparator();
        cmbDate = new com.toedter.calendar.JDateChooser();
        cmbKdDO = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(229, 152, 60));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(248, 246, 233));
        jLabel1.setText("TRANSPORT");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 50, -1, -1));

        jTable1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 1630, 280));

        jPanel7.setBackground(new java.awt.Color(229, 152, 60));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 246, 233)));
        jPanel7.setToolTipText("");

        btnBaru1.setBackground(new java.awt.Color(204, 204, 204));
        btnBaru1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnBaru1.setForeground(new java.awt.Color(248, 246, 233));
        btnBaru1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBaru1.setText("Baru");
        btnBaru1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBaru1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBaru1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBaru1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        jPanel6.setBackground(new java.awt.Color(229, 152, 60));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 246, 233)));
        jPanel6.setToolTipText("");

        btnCetak.setBackground(new java.awt.Color(204, 204, 204));
        btnCetak.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnCetak.setForeground(new java.awt.Color(248, 246, 233));
        btnCetak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCetak.setText("Cetak/Mobil");
        btnCetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCetakMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1360, 470, -1, -1));

        jPanel5.setBackground(new java.awt.Color(229, 152, 60));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 246, 233)));
        jPanel5.setToolTipText("");

        btnHapus1.setBackground(new java.awt.Color(204, 204, 204));
        btnHapus1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnHapus1.setForeground(new java.awt.Color(248, 246, 233));
        btnHapus1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHapus1.setText("Hapus");
        btnHapus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapus1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        jLabel6.setBackground(new java.awt.Color(248, 246, 233));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(248, 246, 233));
        jLabel6.setText("×");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1680, 10, -1, 20));

        jPanel8.setBackground(new java.awt.Color(229, 152, 60));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 246, 233)));
        jPanel8.setToolTipText("");

        btnCetak1.setBackground(new java.awt.Color(204, 204, 204));
        btnCetak1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnCetak1.setForeground(new java.awt.Color(248, 246, 233));
        btnCetak1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCetak1.setText("Cetak/Supp");
        btnCetak1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCetak1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCetak1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCetak1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 470, -1, -1));

        cmbSupp.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cmbSupp.setBorder(null);
        jPanel2.add(cmbSupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 470, 80, 40));

        cmbMbl.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cmbMbl.setBorder(null);
        jPanel2.add(cmbMbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 470, 110, 40));

        jLabel13.setBackground(new java.awt.Color(204, 204, 204));
        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(248, 246, 233));
        jLabel13.setText("Dari");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 400, -1, 40));

        jLabel14.setBackground(new java.awt.Color(204, 204, 204));
        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(248, 246, 233));
        jLabel14.setText("Sampai");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 400, -1, 40));

        cmbDari.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(cmbDari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 400, 160, 40));

        cmbSampai.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(cmbSampai, new org.netbeans.lib.awtextra.AbsoluteConstraints(1500, 400, 160, 40));

        jLabel23.setBackground(new java.awt.Color(204, 204, 204));
        jLabel23.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(248, 246, 233));
        jLabel23.setText("Pilih cetak berdasarkan:");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 480, -1, -1));

        jLabel28.setBackground(new java.awt.Color(204, 204, 204));
        jLabel28.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(248, 246, 233));
        jLabel28.setText("Masukan range tanggal:");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 410, -1, -1));

        jLabel29.setBackground(new java.awt.Color(248, 246, 233));
        jLabel29.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(248, 246, 233));
        jLabel29.setText("?");
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1650, 10, -1, 20));

        jPanel9.setBackground(new java.awt.Color(229, 152, 60));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 246, 233)));
        jPanel9.setToolTipText("");

        btnCetak2.setBackground(new java.awt.Color(204, 204, 204));
        btnCetak2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnCetak2.setForeground(new java.awt.Color(248, 246, 233));
        btnCetak2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCetak2.setText("Cetak Rincian");
        btnCetak2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCetak2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCetak2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCetak2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 470, -1, -1));

        cmbSopir.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cmbSopir.setBorder(null);
        jPanel2.add(cmbSopir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 470, 110, 40));

        jPanel10.setBackground(new java.awt.Color(229, 152, 60));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 246, 233)));
        jPanel10.setToolTipText("");

        btnCetak3.setBackground(new java.awt.Color(204, 204, 204));
        btnCetak3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnCetak3.setForeground(new java.awt.Color(248, 246, 233));
        btnCetak3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCetak3.setText("Cetak/Sopir");
        btnCetak3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCetak3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCetak3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCetak3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 470, -1, -1));

        jPanel3.setBackground(new java.awt.Color(248, 246, 233));
        jPanel3.setForeground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Kode Transport");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        txtKdTransport.setBackground(new java.awt.Color(248, 246, 233));
        txtKdTransport.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtKdTransport.setForeground(new java.awt.Color(102, 102, 102));
        txtKdTransport.setText("Kode Transport");
        txtKdTransport.setBorder(null);
        jPanel3.add(txtKdTransport, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 170, 30));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Tanggal Muat");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Kode Mobil");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("ID Supir");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator5.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 60, 10));

        jSeparator6.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator6.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 170, 10));

        jSeparator7.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator7.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 170, 10));

        jSeparator8.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator8.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 170, 10));

        btnBatal.setBackground(new java.awt.Color(102, 102, 102));
        btnBatal.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(102, 102, 102));
        btnBatal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBatal.setText("Batal");
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
        });
        jPanel3.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 350, 102, 38));

        jPanel4.setBackground(new java.awt.Color(248, 246, 233));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel4.setToolTipText("");

        btnSimpan.setBackground(new java.awt.Color(102, 102, 102));
        btnSimpan.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(102, 102, 102));
        btnSimpan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSimpan.setText("Simpan");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1510, 350, -1, 40));

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Nama Supir");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        jSeparator9.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator9.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 170, 10));

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("DO (Supplier)");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));

        txtDO.setBackground(new java.awt.Color(248, 246, 233));
        txtDO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtDO.setForeground(new java.awt.Color(102, 102, 102));
        txtDO.setText("Delivery Order");
        txtDO.setBorder(null);
        txtDO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDOFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDOFocusLost(evt);
            }
        });
        jPanel3.add(txtDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 170, 30));

        jSeparator10.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator10.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 170, 10));

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Stock Pile (Muat)");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        txtTonasePabrik.setBackground(new java.awt.Color(248, 246, 233));
        txtTonasePabrik.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtTonasePabrik.setForeground(new java.awt.Color(102, 102, 102));
        txtTonasePabrik.setText("0");
        txtTonasePabrik.setBorder(null);
        txtTonasePabrik.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTonasePabrikFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTonasePabrikFocusLost(evt);
            }
        });
        txtTonasePabrik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTonasePabrikKeyReleased(evt);
            }
        });
        jPanel3.add(txtTonasePabrik, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 320, 170, 30));

        jSeparator11.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator11.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 170, 10));

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Kas");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 180, -1, -1));

        txtKas.setBackground(new java.awt.Color(248, 246, 233));
        txtKas.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtKas.setForeground(new java.awt.Color(102, 102, 102));
        txtKas.setText("0");
        txtKas.setBorder(null);
        txtKas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtKasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKasFocusLost(evt);
            }
        });
        txtKas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKasKeyReleased(evt);
            }
        });
        jPanel3.add(txtKas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 170, 170, 30));

        jSeparator12.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator12.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 200, 170, 10));

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Cash In Supplier");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 230, -1, -1));

        txtCashinSupplier.setBackground(new java.awt.Color(248, 246, 233));
        txtCashinSupplier.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCashinSupplier.setForeground(new java.awt.Color(102, 102, 102));
        txtCashinSupplier.setText("0");
        txtCashinSupplier.setBorder(null);
        jPanel3.add(txtCashinSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 220, 170, 30));

        jSeparator13.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator13.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 250, 170, 10));

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Kas Primas");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 280, -1, -1));

        txtKasPrimas.setBackground(new java.awt.Color(248, 246, 233));
        txtKasPrimas.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtKasPrimas.setForeground(new java.awt.Color(102, 102, 102));
        txtKasPrimas.setText("0");
        txtKasPrimas.setBorder(null);
        txtKasPrimas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtKasPrimasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKasPrimasFocusLost(evt);
            }
        });
        jPanel3.add(txtKasPrimas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 270, 170, 30));

        jSeparator14.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator14.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 300, 170, 10));

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Koordinasi");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 330, -1, -1));

        txtKord.setBackground(new java.awt.Color(248, 246, 233));
        txtKord.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtKord.setForeground(new java.awt.Color(102, 102, 102));
        txtKord.setText("0");
        txtKord.setBorder(null);
        txtKord.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtKordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKordFocusLost(evt);
            }
        });
        jPanel3.add(txtKord, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 320, 170, 30));

        jSeparator17.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator17.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 350, 170, 10));

        jLabel16.setBackground(new java.awt.Color(102, 102, 102));
        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Tabungan");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 80, -1, -1));

        txtTab.setBackground(new java.awt.Color(248, 246, 233));
        txtTab.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtTab.setForeground(new java.awt.Color(102, 102, 102));
        txtTab.setText("0");
        txtTab.setBorder(null);
        txtTab.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTabFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTabFocusLost(evt);
            }
        });
        jPanel3.add(txtTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 70, 170, 30));

        jSeparator18.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator18.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 100, 170, 10));

        cmbID.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        cmbID.setBorder(null);
        jPanel3.add(cmbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 60, 30));

        txtNama.setBackground(new java.awt.Color(248, 246, 233));
        txtNama.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNama.setForeground(new java.awt.Color(102, 102, 102));
        txtNama.setText("Nama Supir");
        txtNama.setBorder(null);
        jPanel3.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 170, 30));

        jLabel17.setBackground(new java.awt.Color(102, 102, 102));
        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Tempat Bongkar");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        jSeparator19.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator19.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator19, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 170, 10));

        jLabel18.setBackground(new java.awt.Color(102, 102, 102));
        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Tonase Muat");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        jSeparator20.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator20.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator20, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 170, 10));

        jLabel19.setBackground(new java.awt.Color(102, 102, 102));
        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Tonase Pabrik");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jSeparator21.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator21.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 350, 170, 10));

        jLabel20.setBackground(new java.awt.Color(102, 102, 102));
        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("RP (Harga/Ton)");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 80, -1, -1));

        txtRP.setBackground(new java.awt.Color(248, 246, 233));
        txtRP.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtRP.setForeground(new java.awt.Color(102, 102, 102));
        txtRP.setText("0");
        txtRP.setBorder(null);
        txtRP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRPFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRPFocusLost(evt);
            }
        });
        txtRP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtRPKeyReleased(evt);
            }
        });
        jPanel3.add(txtRP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 70, 170, 30));

        jSeparator22.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator22.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator22, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 100, 170, 10));

        jLabel21.setBackground(new java.awt.Color(102, 102, 102));
        jLabel21.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Jumlah Total");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 130, -1, -1));

        txtJumlahTotal.setBackground(new java.awt.Color(248, 246, 233));
        txtJumlahTotal.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtJumlahTotal.setForeground(new java.awt.Color(102, 102, 102));
        txtJumlahTotal.setText("0");
        txtJumlahTotal.setBorder(null);
        jPanel3.add(txtJumlahTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 120, 170, 30));

        jSeparator23.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator23.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator23, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 150, 170, 10));

        jLabel24.setBackground(new java.awt.Color(102, 102, 102));
        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Cash In Primas");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 130, -1, -1));

        txtCashinPrimas.setBackground(new java.awt.Color(248, 246, 233));
        txtCashinPrimas.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCashinPrimas.setForeground(new java.awt.Color(102, 102, 102));
        txtCashinPrimas.setText("0");
        txtCashinPrimas.setBorder(null);
        jPanel3.add(txtCashinPrimas, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 120, 170, 30));

        jSeparator26.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator26.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 150, 170, 10));

        jLabel25.setBackground(new java.awt.Color(102, 102, 102));
        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("No Surat Jalan");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 180, -1, -1));

        txtNoSJ.setBackground(new java.awt.Color(248, 246, 233));
        txtNoSJ.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNoSJ.setForeground(new java.awt.Color(102, 102, 102));
        txtNoSJ.setText("No Surat Jalan");
        txtNoSJ.setBorder(null);
        txtNoSJ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNoSJFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNoSJFocusLost(evt);
            }
        });
        jPanel3.add(txtNoSJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 170, 170, 30));

        jSeparator27.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator27.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 200, 170, 10));

        jLabel26.setBackground(new java.awt.Color(102, 102, 102));
        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Susut Tonase");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 230, -1, -1));

        txtSusutTonase.setBackground(new java.awt.Color(248, 246, 233));
        txtSusutTonase.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtSusutTonase.setForeground(new java.awt.Color(102, 102, 102));
        txtSusutTonase.setText("0");
        txtSusutTonase.setBorder(null);
        jPanel3.add(txtSusutTonase, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 220, 170, 30));

        jSeparator28.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator28.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator28, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 250, 170, 10));

        jLabel27.setBackground(new java.awt.Color(102, 102, 102));
        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Note");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 280, -1, -1));

        txtNote.setBackground(new java.awt.Color(248, 246, 233));
        txtNote.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNote.setForeground(new java.awt.Color(102, 102, 102));
        txtNote.setText("Note");
        txtNote.setBorder(null);
        txtNote.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNoteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNoteFocusLost(evt);
            }
        });
        txtNote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNoteKeyReleased(evt);
            }
        });
        jPanel3.add(txtNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 270, 170, 30));

        jSeparator29.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator29.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator29, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 300, 170, 10));

        cmbKdMobil.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel3.add(cmbKdMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 60, 30));

        txtTempatBongkar.setBackground(new java.awt.Color(248, 246, 233));
        txtTempatBongkar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtTempatBongkar.setForeground(new java.awt.Color(102, 102, 102));
        txtTempatBongkar.setText("Tempat Bongkar");
        txtTempatBongkar.setBorder(null);
        txtTempatBongkar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTempatBongkarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTempatBongkarFocusLost(evt);
            }
        });
        jPanel3.add(txtTempatBongkar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, 170, 30));

        txtStockpile.setBackground(new java.awt.Color(248, 246, 233));
        txtStockpile.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtStockpile.setForeground(new java.awt.Color(102, 102, 102));
        txtStockpile.setText("Stockpile");
        txtStockpile.setBorder(null);
        txtStockpile.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtStockpileFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtStockpileFocusLost(evt);
            }
        });
        jPanel3.add(txtStockpile, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 170, 30));

        txtTonaseMuat.setBackground(new java.awt.Color(248, 246, 233));
        txtTonaseMuat.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtTonaseMuat.setForeground(new java.awt.Color(102, 102, 102));
        txtTonaseMuat.setText("0");
        txtTonaseMuat.setBorder(null);
        txtTonaseMuat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTonaseMuatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTonaseMuatFocusLost(evt);
            }
        });
        txtTonaseMuat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTonaseMuatKeyReleased(evt);
            }
        });
        jPanel3.add(txtTonaseMuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 270, 170, 30));

        jLabel22.setBackground(new java.awt.Color(102, 102, 102));
        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("NOPOL");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        txtNopol.setBackground(new java.awt.Color(248, 246, 233));
        txtNopol.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNopol.setForeground(new java.awt.Color(102, 102, 102));
        txtNopol.setText("Plat Nomor");
        txtNopol.setBorder(null);
        jPanel3.add(txtNopol, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, 170, 30));

        jSeparator24.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator24.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator24, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 170, 10));

        cmbDate.setDateFormatString("yyyy-MM-dd");
        jPanel3.add(cmbDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 170, -1));

        cmbKdDO.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel3.add(cmbKdDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, 170, 30));

        jLabel30.setBackground(new java.awt.Color(102, 102, 102));
        jLabel30.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("Kode DO");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));

        jSeparator15.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator15.setForeground(new java.awt.Color(242, 233, 242));
        jPanel3.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 60, 10));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1710, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kdTransport() {
        try {
            String sql = "select * from tb_transport ORDER BY LENGTH(kd_transport) desc, kd_transport desc";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet rs=stm.executeQuery(sql);
            if (rs.next()) {
                String kd = rs.getString("kd_transport").substring(3);
                String AN = "" + (Integer.parseInt(kd) + 1);
                txtKdTransport.setText("TRN" + AN);
            } else {
                txtKdTransport.setText("TRN1");
            }

           }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
           }
    }
    
    private void cmbID() {
        try { 
            String sql = "select id_supir from tb_supir ORDER BY LENGTH(id_supir) asc, id_supir asc";
            java.sql.Connection conn=Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                cmbID.addItem(res.getString("id_supir"));
            }
        }catch (Exception e) {
            
        }
        
    }
    
    private void cmbMobil() {
        try { 
            String sql = "select * from tb_mobil ORDER BY LENGTH(kd_mobil) asc, kd_mobil asc";
            java.sql.Connection conn=Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                cmbKdMobil.addItem(res.getString("kd_mobil"));
            }
        }catch (Exception e) {
            
        }
        
    }
    
     private void cmbNopol() {
        try { 
            String sql = "select * from tb_mobil ORDER BY LENGTH(kd_mobil) asc, kd_mobil asc";
            java.sql.Connection conn=Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                cmbMbl.addItem(res.getString("kd_mobil"));
            }
        }catch (Exception e) {
            
        }
        
    }
     
      private void cmbSupp() {
        try { 
            String sql = "SELECT DISTINCT do FROM tb_transport";
            java.sql.Connection conn=Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                cmbSupp.addItem(res.getString("do"));
            }
        }catch (Exception e) {
            
        }
        
    }
      
     private void cmbSpr() {
        try { 
            String sql = "SELECT DISTINCT nm_supir FROM tb_transport";
            java.sql.Connection conn=Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                cmbSopir.addItem(res.getString("nm_supir"));
            }
        }catch (Exception e) {
            
        }
        
    }
      
    private void cmbKdDO() {
        try { 
            String sql = "select * from tb_supplier";
            java.sql.Connection conn=Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                cmbKdDO.addItem(res.getString("kd_do"));
            }
        }catch (Exception e) {
            
        }
        
    }
    
    private void getSupir(){
        try {
            String sql = "SELECT * FROM tb_supir WHERE id_supir = '"+cmbID.getSelectedItem()+"'";
            java.sql.Connection conn=Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            if(res.next() == true) {
                txtNama.setText(res.getString("nm_supir"));
            }
        }catch ( SQLException err ) {
            System.out.println(err.getMessage());
        }   
    }
    
    private void getMobil(){
        try {
            String sql = "SELECT * FROM tb_mobil WHERE kd_mobil = '"+cmbKdMobil.getSelectedItem()+"'";
            java.sql.Connection conn=Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            if(res.next() == true) {
                txtNopol.setText(res.getString("nopol"));
            }
        }catch ( SQLException err ) {
            System.out.println(err.getMessage());
        }   
    }
    
    private void getKdDO(){
        try {
            String sql = "SELECT * FROM tb_supplier WHERE kd_do = '"+cmbKdDO.getSelectedItem()+"'";
            java.sql.Connection conn=Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            if(res.next() == true) {
                txtDO.setText(res.getString("do"));
                txtStockpile.setText(res.getString("stockpile"));
                txtTempatBongkar.setText(res.getString("tempat_bongkar"));
                txtKasPrimas.setText(res.getString("kas_primas"));
                txtKord.setText(res.getString("kord"));
                txtTab.setText(res.getString("tab"));
            }
        }catch ( SQLException err ) {
            System.out.println(err.getMessage());
        }   
    }
    
    private void textboxOn() {
        cmbDate.setEnabled(true);
        cmbKdMobil.setEnabled(true);
        cmbID.setEnabled(true);
        cmbKdDO.setEnabled(true);
        txtTonaseMuat.setEditable(true);
        txtTonasePabrik.setEditable(true);
        txtRP.setEditable(true);
        txtKas.setEditable(true);
        txtCashinPrimas.setEditable(true);
        txtNoSJ.setEditable(true);
        txtNote.setEditable(true);
        jPanel4.setVisible(true);
        btnSimpan.setVisible(true);
        btnBatal.setVisible(true);
    }
    
    private void textboxOff() {
        txtKdTransport.setEnabled(false);
        cmbDate.setEnabled(false);
        cmbKdMobil.setEnabled(false);
        txtNopol.setEnabled(false);
        cmbID.setEnabled(false);
        txtNama.setEnabled(false);
        cmbKdDO.setEnabled(false);
        txtDO.setEnabled(false);
        txtStockpile.setEnabled(false);
        txtTempatBongkar.setEnabled(false);
        txtTonaseMuat.setEditable(false);
        txtTonasePabrik.setEditable(false);
        txtRP.setEditable(false);
        txtJumlahTotal.setEnabled(false);
        txtKas.setEditable(false);
        txtCashinSupplier.setEnabled(false);
        txtKasPrimas.setEnabled(false);
        txtKord.setEnabled(false);
        txtTab.setEnabled(false);
        txtCashinPrimas.setEnabled(false);
        txtNoSJ.setEditable(false);
        txtSusutTonase.setEnabled(false);
        txtNote.setEditable(false);
        jPanel4.setVisible(false);
        btnSimpan.setVisible(false);
        btnBatal.setVisible(false);
        txtNote.setEnabled(false);
    }
    
    private void kosong(){
        txtKdTransport.setText("Kode Transport");
        cmbDate.setDate(null);
        cmbKdMobil.setSelectedItem(null);
        txtNopol.setText("Nopol");
        cmbID.setSelectedItem(null);
        txtNama.setText("Nama Supir");
        cmbKdDO.setSelectedItem(null);
        txtDO.setText("Delivery Order");
        txtStockpile.setText("Stockpile");
        txtTempatBongkar.setText("Tempat Bongkar");
        txtTonaseMuat.setText("0");
        txtTonasePabrik.setText("0");
        txtRP.setText("0");
        txtJumlahTotal.setText("0");
        txtKas.setText("0");
        txtCashinSupplier.setText("0");
        txtKasPrimas.setText("0");
        txtKord.setText("0");
        txtTab.setText("0");
        txtCashinPrimas.setText("0");
        txtNoSJ.setText("");
        txtSusutTonase.setText("0");
        txtNote.setText("Note");
    }
    
    private void load_table(){
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Trans");
        model.addColumn("Tanggal");
        model.addColumn("Kode Mobil");
        model.addColumn("NOPOL");
        model.addColumn("ID Supir");
        model.addColumn("Nama");
        model.addColumn("DO");
        model.addColumn("Stock Pile");
        model.addColumn("Tempat Bongkar");
        model.addColumn("Tonase Muat");
        model.addColumn("Tonase Pabrik");
        model.addColumn("RP");
        model.addColumn("Jumlah Total");
        model.addColumn("Kas");
        model.addColumn("Cashin Supp");
        model.addColumn("Kas Primas");
        model.addColumn("Kord");
        model.addColumn("Tab");
        model.addColumn("Cashin Primas");
        model.addColumn("No SJ");
        model.addColumn("Susut Tonase");
        model.addColumn("Note");
        
        //menampilkan data database kedalam tabel
        try {
            String sql = "select * from tb_transport ORDER BY LENGTH(kd_transport) asc, kd_transport asc";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8),res.getString(9),res.getString(10),res.getString(11),res.getString(12),res.getString(13),res.getString(14),res.getString(15),res.getString(16),res.getString(17),res.getString(18),res.getString(19),res.getString(20),res.getString(21),res.getString(22)});
            }
            jTable1.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
//        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF );

        for (int column = 0; column < jTable1.getColumnCount(); column++){
            TableColumn tableColumn = jTable1.getColumnModel().getColumn(column);
            int preferredWidth = tableColumn.getMinWidth();
            int maxWidth = 0;
            TableCellRenderer rend = jTable1.getTableHeader().getDefaultRenderer();
            TableCellRenderer rendCol = tableColumn.getHeaderRenderer();
            if (rendCol == null) rendCol = rend;
            Component header = rendCol.getTableCellRendererComponent(jTable1, tableColumn.getHeaderValue(), false, false, 0, column);
            maxWidth = header.getPreferredSize().width;
            System.out.println("maxWidth :"+maxWidth);

            for (int row = 0; row < jTable1.getRowCount(); row++){
                TableCellRenderer cellRenderer = jTable1.getCellRenderer(row, column);
                Component c = jTable1.prepareRenderer(cellRenderer, row, column);
                int width = c.getPreferredSize().width + jTable1.getIntercellSpacing().width;
                preferredWidth = Math.max(preferredWidth, width);
                System.out.println("preferredWidth :"+preferredWidth);
                System.out.println("Width :"+width);

                //  We've exceeded the maximum width, no need to check other rows

                if (preferredWidth <= maxWidth){
                    preferredWidth = maxWidth;
                    break;
                }
            }
            tableColumn.setPreferredWidth(preferredWidth);
        }
    }
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
                int baris = jTable1.rowAtPoint(evt.getPoint());
                String kdtransport =jTable1.getValueAt(baris, 0).toString();
                txtKdTransport.setText(kdtransport);
                String tgl = jTable1.getValueAt(baris,1).toString();
                 try{
                        java.util.Date date;
                        date = new SimpleDateFormat("yyyy-MM-dd").parse(tgl);
                        cmbDate.setDate(date);
                    } catch (ParseException ex) {
                        Logger.getLogger(frmOli.class.getName()).log(Level.SEVERE, null, ex);
                    }
                String kdmobil=jTable1.getValueAt(baris, 2).toString();
                cmbKdMobil.setSelectedItem(kdmobil);
                String nopol = jTable1.getValueAt(baris, 3).toString();
                txtNopol.setText(nopol);
                String id =jTable1.getValueAt(baris, 4).toString();
                cmbID.setSelectedItem(id);
                String nama = jTable1.getValueAt(baris,5).toString();
                txtNama.setText(nama);
                String deo=jTable1.getValueAt(baris, 6).toString();
                txtDO.setText(deo);
                String stokpile = jTable1.getValueAt(baris, 7).toString();
                txtStockpile.setText(stokpile);
                String bongkar =jTable1.getValueAt(baris, 8).toString();
                txtTempatBongkar.setText(bongkar);
                String tonmuat = jTable1.getValueAt(baris,9).toString();
                txtTonaseMuat.setText(tonmuat);
                String tonpabrik=jTable1.getValueAt(baris, 10).toString();
                txtTonasePabrik.setText(tonpabrik);
                String rp = jTable1.getValueAt(baris, 11).toString();
                txtRP.setText(rp);
                String jumlahtotal = jTable1.getValueAt(baris, 12).toString();
                txtJumlahTotal.setText(jumlahtotal);
                String kas =jTable1.getValueAt(baris, 13).toString();
                txtKas.setText(kas);
                String cashinsupp = jTable1.getValueAt(baris,14).toString();
                txtCashinSupplier.setText(cashinsupp);
                String kasprimas=jTable1.getValueAt(baris, 15).toString();
                txtKasPrimas.setText(kasprimas);
                String kord = jTable1.getValueAt(baris,16).toString();
                txtKord.setText(kord);
                String tab=jTable1.getValueAt(baris, 17).toString();
                txtTab.setText(tab);
                String cashinprimas = jTable1.getValueAt(baris, 18).toString();
                txtCashinPrimas.setText(cashinprimas);
                String nosj =jTable1.getValueAt(baris, 19).toString();
                txtNoSJ.setText(nosj);
                String susuttonase = jTable1.getValueAt(baris,20).toString();
                txtSusutTonase.setText(susuttonase);
                String note = jTable1.getValueAt(baris, 21).toString();
                txtNote.setText(note);
                textboxOn();
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnBaru1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBaru1MouseClicked
        // TODO add your handling code here:
                textboxOn();
                kosong();
                kdTransport();
    }//GEN-LAST:event_btnBaru1MouseClicked

    private void btnCetakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCetakMouseClicked
        // TODO add your handling code here:
         HashMap param = new HashMap();
                    param.put("mobil1",cmbMbl.getSelectedItem());
                    param.put("dari1",cmbDari.getDate());
                    param.put("sampai1",cmbSampai.getDate());
                try {
                        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("rptTransportMobil.jasper"), param, Config.configDB());
                        JasperViewer.viewReport(jp, false);
                        
                    } catch(Exception e) {
                        JOptionPane.showMessageDialog(rootPane, e);
                    }
    }//GEN-LAST:event_btnCetakMouseClicked

    private void btnHapus1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapus1MouseClicked
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Benarkah anda ingin menghapus data ini?", "Penghapusan Data", JOptionPane.YES_NO_OPTION);
        if (opsi == JOptionPane.YES_OPTION){
            try {
                String sql ="delete from tb_transport where kd_transport='"+txtKdTransport.getText()+"'";
                java.sql.Connection conn=(Connection)Config.configDB();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            load_table();
            kosong();
        }else{
            JOptionPane.showMessageDialog(null, "Data batal dihapus.");
        }
    }//GEN-LAST:event_btnHapus1MouseClicked

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        textboxOff();
        kosong();
    }//GEN-LAST:event_btnBatalMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.dispose();
        new mainMenu().setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        try{
            String query = "select * from tb_transport where kd_transport = '"+txtKdTransport.getText()+"'";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(query);
            SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd");
            if(res.next()){
                    String sql ="UPDATE tb_transport SET kd_transport = '"+txtKdTransport.getText()+"', tgl_muat = '"+Date_Format.format(cmbDate.getDate())+"', kd_mobil = '"+cmbKdMobil.getSelectedItem()+"',nopol= '"+txtNopol.getText()+"', id_supir = '"+cmbID.getSelectedItem()+"', nm_supir = '"+txtNama.getText()+"', do = '"+txtDO.getText()+"',stockpile= '"+txtStockpile.getText()+"', tempat_bongkar = '"+txtTempatBongkar.getText()+"', tonase_muat = '"+txtTonaseMuat.getText()+"', tonase_pabrik = '"+txtTonasePabrik.getText()+"',rp= '"+txtRP.getText()+"',jumlah_total= '"+txtJumlahTotal.getText()+"', kas= '"+txtKas.getText()+"', cashin_dr_sply = '"+txtCashinSupplier.getText()+"', kas_primas = '"+txtKasPrimas.getText()+"', kord = '"+txtKord.getText()+"', tab = '"+txtTab.getText()+"', cashin_primas = '"+txtCashinPrimas.getText()+"',no_sj= '"+txtNoSJ.getText()+"',susut_tonase= '"+txtSusutTonase.getText()+"',note= '"+txtNote.getText()+"' WHERE kd_transport = '"+txtKdTransport.getText()+"'";
                    java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "data berhasil diedit");
                }else{
                    String sql = "INSERT INTO tb_transport VALUES ('"+txtKdTransport.getText()+"','"+Date_Format.format(cmbDate.getDate())+"','"+cmbKdMobil.getSelectedItem()+"', '"+txtNopol.getText()+"','"+cmbID.getSelectedItem()+"','"+txtNama.getText()+"','"+txtDO.getText()+"','"+txtStockpile.getText()+"','"+txtTempatBongkar.getText()+"','"+txtTonaseMuat.getText()+"','"+txtTonasePabrik.getText()+"','"+txtRP.getText()+"','"+txtJumlahTotal.getText()+"','"+txtKas.getText()+"','"+txtCashinSupplier.getText()+"','"+txtKasPrimas.getText()+"','"+txtKord.getText()+"','"+txtTab.getText()+"','"+txtCashinPrimas.getText()+"','"+txtNoSJ.getText()+"','"+txtSusutTonase.getText()+"','"+txtNote.getText()+"')";
                    java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(null, "Penyimpanan data berhasil");
                }
            load_table();
            textboxOff();
            kosong();
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void txtDOFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDOFocusGained
        if (txtDO.getText().equals("Delivery Order")){
            txtDO.setText("");
        }
    }//GEN-LAST:event_txtDOFocusGained

    private void txtDOFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDOFocusLost
        if (txtDO.getText().equals("")){
            txtDO.setText("Delivery Order");
        }
    }//GEN-LAST:event_txtDOFocusLost

    private void txtTonasePabrikFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTonasePabrikFocusGained
        // TODO add your handling code here:
        if (txtTonasePabrik.getText().equals("0")){
            txtTonasePabrik.setText("");
        }
    }//GEN-LAST:event_txtTonasePabrikFocusGained

    private void txtTonasePabrikFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTonasePabrikFocusLost
        // TODO add your handling code here:
        if (txtTonasePabrik.getText().equals("")){
            txtTonasePabrik.setText("0");
        }
    }//GEN-LAST:event_txtTonasePabrikFocusLost

    private void txtTonasePabrikKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTonasePabrikKeyReleased
        jumlahtotal();
        susuttonase();
        cashinsupplier();
        cashinprimas();
    }//GEN-LAST:event_txtTonasePabrikKeyReleased

    private void txtKasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKasFocusGained
        if (txtKas.getText().equals("0")){
            txtKas.setText("");
        }
    }//GEN-LAST:event_txtKasFocusGained

    private void txtKasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKasFocusLost
        if (txtKas.getText().equals("")){
            txtKas.setText("0");
        }
    }//GEN-LAST:event_txtKasFocusLost

    private void txtKasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKasKeyReleased
        jumlahtotal();
        susuttonase();
        cashinsupplier();
        cashinprimas();
        notes();
    }//GEN-LAST:event_txtKasKeyReleased

    private void txtKordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKordFocusGained
        if (txtKord.getText().equals("0")){
            txtKord.setText("");
        }
    }//GEN-LAST:event_txtKordFocusGained

    private void txtKordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKordFocusLost
        if (txtKord.getText().equals("")){
            txtKord.setText("0");
        }
    }//GEN-LAST:event_txtKordFocusLost

    private void txtTabFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTabFocusGained
        if (txtTab.getText().equals("0")){
            txtTab.setText("");
        }
    }//GEN-LAST:event_txtTabFocusGained

    private void txtTabFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTabFocusLost
        if (txtTab.getText().equals("")){
            txtTab.setText("0");
        }
    }//GEN-LAST:event_txtTabFocusLost

    private void txtNoSJFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNoSJFocusGained
//        if (txtNoSJ.getText().equals("No Surat Jln")){
//            txtNoSJ.setText("");
//        }
    }//GEN-LAST:event_txtNoSJFocusGained

    private void txtNoSJFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNoSJFocusLost
//        if (txtTab.getText().equals("")){
//            txtTab.setText("No Surat Jln");
//        }
    }//GEN-LAST:event_txtNoSJFocusLost

    private void txtNoteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNoteFocusGained
        if (txtNote.getText().equals("Note")){
            txtNote.setText("");
        }
    }//GEN-LAST:event_txtNoteFocusGained

    private void txtNoteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNoteFocusLost
        if (txtNote.getText().equals("")){
            txtNote.setText("Note");
        }
    }//GEN-LAST:event_txtNoteFocusLost

    private void txtNoteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNoteKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoteKeyReleased

    private void txtStockpileFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStockpileFocusGained
        if (txtStockpile.getText().equals("Stockpile")){
            txtStockpile.setText("");
        }
    }//GEN-LAST:event_txtStockpileFocusGained

    private void txtStockpileFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtStockpileFocusLost
        if (txtStockpile.getText().equals("")){
            txtStockpile.setText("Stockpile");
        }
    }//GEN-LAST:event_txtStockpileFocusLost

    private void txtTonaseMuatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTonaseMuatFocusGained
        if (txtTonaseMuat.getText().equals("0")){
            txtTonaseMuat.setText("");
        }
    }//GEN-LAST:event_txtTonaseMuatFocusGained

    private void txtTonaseMuatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTonaseMuatFocusLost
        if (txtTonaseMuat.getText().equals("")){
            txtTonaseMuat.setText("0");
        }
    }//GEN-LAST:event_txtTonaseMuatFocusLost

    private void txtTonaseMuatKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTonaseMuatKeyReleased
        jumlahtotal();
        susuttonase();
        cashinsupplier();
        cashinprimas();
    }//GEN-LAST:event_txtTonaseMuatKeyReleased

    private void cmbIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbIDActionPerformed

    private void txtTempatBongkarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTempatBongkarFocusGained
        if (txtTempatBongkar.getText().equals("Tempat Bongkar")){
            txtTempatBongkar.setText("");
        }
    }//GEN-LAST:event_txtTempatBongkarFocusGained

    private void txtTempatBongkarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTempatBongkarFocusLost
        if (txtTempatBongkar.getText().equals("")){
            txtTempatBongkar.setText("Tempat Bongkar");
        }
    }//GEN-LAST:event_txtTempatBongkarFocusLost

    private void txtRPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRPFocusGained
        if (txtRP.getText().equals("0")){
            txtRP.setText("");
        }
    }//GEN-LAST:event_txtRPFocusGained

    private void txtRPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRPFocusLost
        if (txtRP.getText().equals("")){
            txtRP.setText("0");
        }
    }//GEN-LAST:event_txtRPFocusLost

    private void txtKasPrimasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKasPrimasFocusGained
        if (txtKasPrimas.getText().equals("0")){
            txtKasPrimas.setText("");
        }
    }//GEN-LAST:event_txtKasPrimasFocusGained

    private void txtKasPrimasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKasPrimasFocusLost
        if (txtKasPrimas.getText().equals("")){
            txtKasPrimas.setText("0");
        }
    }//GEN-LAST:event_txtKasPrimasFocusLost

    private void txtRPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRPKeyReleased
        jumlahtotal();
        susuttonase();
        cashinsupplier();
        cashinprimas();
    }//GEN-LAST:event_txtRPKeyReleased

    private void btnCetak1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCetak1MouseClicked
        // TODO add your handling code here:
        HashMap param = new HashMap();
                    param.put("do1",cmbSupp.getSelectedItem());
                    param.put("dari1",cmbDari.getDate());
                    param.put("sampai1",cmbSampai.getDate());
                try {
                        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("rptTransportSupp.jasper"), param, Config.configDB());
                        JasperViewer.viewReport(jp, false);
                        
                    } catch(Exception e) {
                        JOptionPane.showMessageDialog(rootPane, e);
                    }
    }//GEN-LAST:event_btnCetak1MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Form Transport.\n - Mengisikan data: Klik 'Baru' lalu form akan tersedia untuk diisi.\n - Mengubah data: Piih data lalu klik pada tabel, data akan muncul di form untuk diubah.\n - Menghapus data: Piih data lalu klik pada tabel, lalu tekan tombol 'Hapus' data akan terhapus.\n - Mencetak laporan: Masukan tanggal dari dan sampai lalu pilih Cetak Rincian atau berdasarkan Mobil atau Supplier");
    }//GEN-LAST:event_jLabel29MouseClicked
    int xy, xx;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btnCetak2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCetak2MouseClicked
        // TODO add your handling code here:
         HashMap param = new HashMap();
                    param.put("dari1",cmbDari.getDate());
                    param.put("sampai1",cmbSampai.getDate());
                try {
                        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("rptTransport.jasper"), param, Config.configDB());
                        JasperViewer.viewReport(jp, false);
                        
                    } catch(Exception e) {
                        JOptionPane.showMessageDialog(rootPane, e);
                    }
    }//GEN-LAST:event_btnCetak2MouseClicked

    private void btnCetak3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCetak3MouseClicked
        // TODO add your handling code here:
        HashMap param = new HashMap();
                    param.put("supir1",cmbSopir.getSelectedItem());
                    param.put("dari1",cmbDari.getDate());
                    param.put("sampai1",cmbSampai.getDate());
                try {
                        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("rptTransportSupir.jasper"), param, Config.configDB());
                        JasperViewer.viewReport(jp, false);
                        
                    } catch(Exception e) {
                        JOptionPane.showMessageDialog(rootPane, e);
                    }
    }//GEN-LAST:event_btnCetak3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTransport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTransport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTransport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTransport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTransport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBaru1;
    private javax.swing.JLabel btnBatal;
    private javax.swing.JLabel btnCetak;
    private javax.swing.JLabel btnCetak1;
    private javax.swing.JLabel btnCetak2;
    private javax.swing.JLabel btnCetak3;
    private javax.swing.JLabel btnHapus1;
    private javax.swing.JLabel btnSimpan;
    private com.toedter.calendar.JDateChooser cmbDari;
    private com.toedter.calendar.JDateChooser cmbDate;
    private javax.swing.JComboBox<String> cmbID;
    private javax.swing.JComboBox<String> cmbKdDO;
    private javax.swing.JComboBox<String> cmbKdMobil;
    private javax.swing.JComboBox<String> cmbMbl;
    private com.toedter.calendar.JDateChooser cmbSampai;
    private javax.swing.JComboBox<String> cmbSopir;
    private javax.swing.JComboBox<String> cmbSupp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCashinPrimas;
    private javax.swing.JTextField txtCashinSupplier;
    private javax.swing.JTextField txtDO;
    private javax.swing.JTextField txtJumlahTotal;
    private javax.swing.JTextField txtKas;
    private javax.swing.JTextField txtKasPrimas;
    private javax.swing.JTextField txtKdTransport;
    private javax.swing.JTextField txtKord;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoSJ;
    private javax.swing.JTextField txtNopol;
    private javax.swing.JTextField txtNote;
    private javax.swing.JTextField txtRP;
    private javax.swing.JTextField txtStockpile;
    private javax.swing.JTextField txtSusutTonase;
    private javax.swing.JTextField txtTab;
    private javax.swing.JTextField txtTempatBongkar;
    private javax.swing.JTextField txtTonaseMuat;
    private javax.swing.JTextField txtTonasePabrik;
    // End of variables declaration//GEN-END:variables
}
