/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package primastrans;

/**
 *
 * @author R
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.*;
import net.sf.jasperreports.view.*;
import net.sf.jasperreports.engine.*;

public class frmUpahSupir extends javax.swing.JFrame {
    public Connection conn;
    public ResultSet res;
    public PreparedStatement pst;

    /**
     * Creates new form frmUpahSupir
     */
    public frmUpahSupir() {
        initComponents();
        this.setLocationRelativeTo(null);
        load_table();
        cmbID();
        cmbMobil();
        kosong();
        textboxOff();
        
        cmbID.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                getSupir();
            }
        });
        
        cmbMobil.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
                getMobil();
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        btnBaru1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnCetak = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnHapus1 = new javax.swing.JLabel();
        cmbSampai = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cmbDari = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtKdUpah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        btnBatal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNopol = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtBayaran = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtKoordinasi = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtSubsidi = new javax.swing.JTextField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        txtBon = new javax.swing.JTextField();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        txtPotongan = new javax.swing.JTextField();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        txtUpah = new javax.swing.JTextField();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        txtNote = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        cmbID = new javax.swing.JComboBox<>();
        cmbMobil = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        cmbDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(61, 115, 80));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("UPAH SUPIR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 780, 260));

        jPanel7.setBackground(new java.awt.Color(61, 115, 80));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel7.setToolTipText("");

        btnBaru1.setBackground(new java.awt.Color(204, 204, 204));
        btnBaru1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBaru1.setForeground(new java.awt.Color(204, 204, 204));
        btnBaru1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBaru1.setText("Baru");
        btnBaru1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBaru1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBaru1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBaru1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jPanel6.setBackground(new java.awt.Color(61, 115, 80));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel6.setToolTipText("");

        btnCetak.setBackground(new java.awt.Color(204, 204, 204));
        btnCetak.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCetak.setForeground(new java.awt.Color(204, 204, 204));
        btnCetak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCetak.setText("Cetak");
        btnCetak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCetakMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, -1, -1));

        jPanel5.setBackground(new java.awt.Color(61, 115, 80));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel5.setToolTipText("");

        btnHapus1.setBackground(new java.awt.Color(204, 204, 204));
        btnHapus1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnHapus1.setForeground(new java.awt.Color(204, 204, 204));
        btnHapus1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHapus1.setText("Hapus");
        btnHapus1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapus1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnHapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        cmbSampai.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(cmbSampai, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 140, 30));

        jLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Dari");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, -1, 40));

        jLabel18.setBackground(new java.awt.Color(204, 204, 204));
        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Sampai");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, -1, 40));

        cmbDari.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(cmbDari, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 410, 140, 30));

        jPanel2.setBackground(new java.awt.Color(242, 233, 242));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Tanggal");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        txtKdUpah.setBackground(new java.awt.Color(242, 233, 242));
        txtKdUpah.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtKdUpah.setForeground(new java.awt.Color(102, 102, 102));
        txtKdUpah.setText("Kode Upah");
        txtKdUpah.setBorder(null);
        jPanel2.add(txtKdUpah, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 170, 30));

        jLabel3.setBackground(new java.awt.Color(102, 102, 102));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("ID Supir");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, -1, -1));

        txtNama.setBackground(new java.awt.Color(242, 233, 242));
        txtNama.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNama.setForeground(new java.awt.Color(102, 102, 102));
        txtNama.setText("Nama");
        txtNama.setBorder(null);
        jPanel2.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 170, 30));

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Nama");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Kode Mobil");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator5.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 120, 10));

        jSeparator6.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator6.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 120, 10));

        jSeparator7.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator7.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 120, 10));

        jSeparator8.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator8.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 170, 10));

        btnBatal.setBackground(new java.awt.Color(102, 102, 102));
        btnBatal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(102, 102, 102));
        btnBatal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBatal.setText("Batal");
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
        });
        jPanel2.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 102, 38));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("×");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, -1, 20));

        jPanel4.setBackground(new java.awt.Color(242, 233, 242));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel4.setToolTipText("");

        btnSimpan.setBackground(new java.awt.Color(102, 102, 102));
        btnSimpan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(102, 102, 102));
        btnSimpan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnSimpan.setText("Simpan");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 490, -1, 40));

        jLabel7.setBackground(new java.awt.Color(102, 102, 102));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("NOPOL");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        txtNopol.setBackground(new java.awt.Color(242, 233, 242));
        txtNopol.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNopol.setForeground(new java.awt.Color(102, 102, 102));
        txtNopol.setText("NOPOL");
        txtNopol.setBorder(null);
        jPanel2.add(txtNopol, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 170, 30));

        jSeparator9.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator9.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 170, 10));

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Bayaran");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, -1, -1));

        txtBayaran.setBackground(new java.awt.Color(242, 233, 242));
        txtBayaran.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtBayaran.setForeground(new java.awt.Color(102, 102, 102));
        txtBayaran.setText("Bayaran");
        txtBayaran.setBorder(null);
        txtBayaran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBayaranFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBayaranFocusLost(evt);
            }
        });
        txtBayaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBayaranKeyReleased(evt);
            }
        });
        jPanel2.add(txtBayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 170, 30));

        jSeparator10.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator10.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 170, 10));

        jLabel9.setBackground(new java.awt.Color(102, 102, 102));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Koordinasi");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, -1, -1));

        txtKoordinasi.setBackground(new java.awt.Color(242, 233, 242));
        txtKoordinasi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtKoordinasi.setForeground(new java.awt.Color(102, 102, 102));
        txtKoordinasi.setText("Koordinasi");
        txtKoordinasi.setBorder(null);
        txtKoordinasi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtKoordinasiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKoordinasiFocusLost(evt);
            }
        });
        txtKoordinasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtKoordinasiKeyReleased(evt);
            }
        });
        jPanel2.add(txtKoordinasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 170, 30));

        jSeparator11.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator11.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 170, 10));

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Subsidi");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        txtSubsidi.setBackground(new java.awt.Color(242, 233, 242));
        txtSubsidi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtSubsidi.setForeground(new java.awt.Color(102, 102, 102));
        txtSubsidi.setText("Subsidi");
        txtSubsidi.setBorder(null);
        txtSubsidi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSubsidiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSubsidiFocusLost(evt);
            }
        });
        txtSubsidi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSubsidiKeyReleased(evt);
            }
        });
        jPanel2.add(txtSubsidi, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 170, 30));

        jSeparator12.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator12.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, 170, 10));

        jLabel11.setBackground(new java.awt.Color(102, 102, 102));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Bon");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        txtBon.setBackground(new java.awt.Color(242, 233, 242));
        txtBon.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtBon.setForeground(new java.awt.Color(102, 102, 102));
        txtBon.setText("Bon");
        txtBon.setBorder(null);
        txtBon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBonFocusLost(evt);
            }
        });
        txtBon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBonKeyReleased(evt);
            }
        });
        jPanel2.add(txtBon, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 170, 30));

        jSeparator13.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator13.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 170, 10));

        jLabel12.setBackground(new java.awt.Color(102, 102, 102));
        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Total");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        txtTotal.setBackground(new java.awt.Color(242, 233, 242));
        txtTotal.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(102, 102, 102));
        txtTotal.setText("Total");
        txtTotal.setBorder(null);
        jPanel2.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 170, 30));

        jSeparator14.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator14.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 170, 10));

        jLabel13.setBackground(new java.awt.Color(102, 102, 102));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Potongan");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));

        txtPotongan.setBackground(new java.awt.Color(242, 233, 242));
        txtPotongan.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPotongan.setForeground(new java.awt.Color(102, 102, 102));
        txtPotongan.setText("Potongan");
        txtPotongan.setBorder(null);
        txtPotongan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPotonganFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPotonganFocusLost(evt);
            }
        });
        txtPotongan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPotonganKeyReleased(evt);
            }
        });
        jPanel2.add(txtPotongan, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 310, 170, 30));

        jSeparator15.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator15.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 170, 10));

        jLabel14.setBackground(new java.awt.Color(102, 102, 102));
        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Upah");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));

        txtUpah.setBackground(new java.awt.Color(242, 233, 242));
        txtUpah.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtUpah.setForeground(new java.awt.Color(102, 102, 102));
        txtUpah.setText("Upah");
        txtUpah.setBorder(null);
        jPanel2.add(txtUpah, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 170, 30));

        jSeparator16.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator16.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 170, 10));

        jLabel15.setBackground(new java.awt.Color(102, 102, 102));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Note");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        txtNote.setBackground(new java.awt.Color(242, 233, 242));
        txtNote.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNote.setForeground(new java.awt.Color(102, 102, 102));
        txtNote.setText("Note");
        txtNote.setBorder(null);
        txtNote.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNoteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNoteFocusLost(evt);
            }
        });
        jPanel2.add(txtNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 170, 30));

        jSeparator17.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator17.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 170, 10));

        cmbID.setBackground(new java.awt.Color(242, 233, 242));
        cmbID.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cmbID.setForeground(new java.awt.Color(102, 102, 102));
        cmbID.setBorder(null);
        cmbID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIDActionPerformed(evt);
            }
        });
        jPanel2.add(cmbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 120, 30));

        cmbMobil.setBackground(new java.awt.Color(242, 233, 242));
        cmbMobil.setForeground(new java.awt.Color(102, 102, 102));
        cmbMobil.setBorder(null);
        jPanel2.add(cmbMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 120, 30));

        jLabel16.setBackground(new java.awt.Color(102, 102, 102));
        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Kode Upah");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        jSeparator18.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator18.setForeground(new java.awt.Color(242, 233, 242));
        jPanel2.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 170, 10));

        cmbDate.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(cmbDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int baris = jTable1.rowAtPoint(evt.getPoint());
        String kdupah =jTable1.getValueAt(baris, 0).toString();
        txtKdUpah.setText(kdupah);
        String id = jTable1.getValueAt(baris,1).toString();
        cmbID.setSelectedItem(id);
        String nama=jTable1.getValueAt(baris, 2).toString();
        txtNama.setText(nama);
        String kdmobil = jTable1.getValueAt(baris, 3).toString();
        cmbMobil.setSelectedItem(kdmobil);
        String nopol =jTable1.getValueAt(baris, 4).toString();
        txtNopol.setText(nopol);
        String bayaran = jTable1.getValueAt(baris,5).toString();
        txtBayaran.setText(bayaran);
        String koordinasi=jTable1.getValueAt(baris, 6).toString();
        txtKoordinasi.setText(koordinasi);
        String subsidi = jTable1.getValueAt(baris, 7).toString();
        txtSubsidi.setText(subsidi);
        String bon =jTable1.getValueAt(baris, 8).toString();
        txtBon.setText(bon);
        String total = jTable1.getValueAt(baris,9).toString();
        txtTotal.setText(total);
        String potongan=jTable1.getValueAt(baris, 10).toString();
        txtPotongan.setText(potongan);
        String upah = jTable1.getValueAt(baris, 11).toString();
        txtUpah.setText(upah);
        String note = jTable1.getValueAt(baris, 12).toString();
        txtNote.setText(note);
        String tgl = jTable1.getValueAt(baris,13).toString();
        try {
            java.util.Date date;
            date = new SimpleDateFormat("yyyy-MM-dd").parse(tgl);
            cmbDate.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(frmOli.class.getName()).log(Level.SEVERE, null, ex);
        }
        textboxOn();
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnBaru1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBaru1MouseClicked
        // TODO add your handling code here:
        textboxOn();
        kosong();
        kdUpah();
    }//GEN-LAST:event_btnBaru1MouseClicked

    private void btnCetakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCetakMouseClicked
        // TODO add your handling code here:
       HashMap param = new HashMap();
                    param.put("Dari Tanggal",cmbDari.getDate());
                    param.put("Sampai",cmbSampai.getDate());
                try {
                        JasperPrint jp = JasperFillManager.fillReport(getClass().getResourceAsStream("rptUpah.jasper"), param, Config.configDB());
                        JasperViewer.viewReport(jp, false);
                        
                    } catch(Exception e) {
                        JOptionPane.showMessageDialog(rootPane, e);
                    }
    }//GEN-LAST:event_btnCetakMouseClicked

    private void btnHapus1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapus1MouseClicked
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Benarkah anda ingin menghapus data ini?", "Penghapusan Data", JOptionPane.YES_NO_OPTION);
        if (opsi == JOptionPane.YES_OPTION){
            try {
                String sql ="delete from tb_upah_supir where kd_upah='"+txtKdUpah.getText()+"'";
                java.sql.Connection conn=(Connection)Config.configDB();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(this, "Data berhasil di hapus.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            load_table();
            kosong();
        }else{
            JOptionPane.showMessageDialog(null, "Data batal dihapus.");
        }
    }//GEN-LAST:event_btnHapus1MouseClicked

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        // TODO add your handling code here:
        textboxOff();
        kosong();
    }//GEN-LAST:event_btnBatalMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        this.dispose();
        new mainMenu().setVisible(true);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        // TODO add your handling code here:
        try{
            String query = "select * from tb_upah_supir where kd_upah = '"+txtKdUpah.getText()+"'";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(query);
            SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd");
            if(res.next()){
                String sql ="UPDATE tb_upah_supir SET kd_upah = '"+txtKdUpah.getText()+"', id_supir = '"+cmbID.getSelectedItem()+"', nm_supir = '"+txtNama.getText()+"',kd_mobil= '"+cmbMobil.getSelectedItem()+"', nopol = '"+txtNopol.getText()+"', bayaran = '"+txtBayaran.getText()+"', koordinasi = '"+txtKoordinasi.getText()+"',subsidi= '"+txtSubsidi.getText()+"', bon = '"+txtBon.getText()+"', total = '"+txtTotal.getText()+"', potongan = '"+txtPotongan.getText()+"',upah= '"+txtUpah.getText()+"',note= '"+txtNote.getText()+"',tgl = '"+Date_Format.format(cmbDate.getDate())+"' WHERE kd_upah = '"+txtKdUpah.getText()+"'";
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "data berhasil diedit");
            }else{
                String sql = "INSERT INTO tb_upah_supir VALUES ('"+txtKdUpah.getText()+"','"+cmbID.getSelectedItem()+"','"+txtNama.getText()+"','"+cmbMobil.getSelectedItem()+"', '"+txtNopol.getText()+"', '"+txtBayaran.getText()+"', '"+txtKoordinasi.getText()+"', '"+txtSubsidi.getText()+"', '"+txtBon.getText()+"', '"+txtTotal.getText()+"', '"+txtPotongan.getText()+"', '"+txtUpah.getText()+"', '"+txtNote.getText()+"','"+Date_Format.format(cmbDate.getDate())+"')";
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Penyimpanan data berhasil");
            }
            load_table();  
            textboxOff();
            kosong();
        }catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void txtBayaranFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBayaranFocusGained
        // TODO add your handling code here:
        if (txtBayaran.getText().equals("0")){
        txtBayaran.setText("");
        }
    }//GEN-LAST:event_txtBayaranFocusGained

    private void txtKoordinasiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKoordinasiFocusGained
        // TODO add your handling code here:
        if (txtKoordinasi.getText().equals("0")){
        txtKoordinasi.setText("");
        }
    }//GEN-LAST:event_txtKoordinasiFocusGained

    private void txtSubsidiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubsidiFocusGained
        // TODO add your handling code here:
        if (txtSubsidi.getText().equals("0")){
        txtSubsidi.setText("");
        }
    }//GEN-LAST:event_txtSubsidiFocusGained

    private void txtBonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBonFocusGained
        // TODO add your handling code here:
        if (txtBon.getText().equals("0")){
        txtBon.setText("");
        }
    }//GEN-LAST:event_txtBonFocusGained

    private void txtPotonganFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPotonganFocusGained
        // TODO add your handling code here:
        if (txtPotongan.getText().equals("0")){
        txtPotongan.setText("");
        }
    }//GEN-LAST:event_txtPotonganFocusGained

    private void txtNoteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNoteFocusGained
        // TODO add your handling code here:
        if (txtNote.getText().equals("Note")){
        txtNote.setText("");
        }
    }//GEN-LAST:event_txtNoteFocusGained

    private void txtBayaranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBayaranKeyReleased
        // TODO add your handling code here:
        total();
    }//GEN-LAST:event_txtBayaranKeyReleased

    private void txtKoordinasiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKoordinasiKeyReleased
        // TODO add your handling code here:
        total();
    }//GEN-LAST:event_txtKoordinasiKeyReleased

    private void txtSubsidiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubsidiKeyReleased
        // TODO add your handling code here:
        total();
    }//GEN-LAST:event_txtSubsidiKeyReleased

    private void txtBonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBonKeyReleased
        // TODO add your handling code here:
        total();
    }//GEN-LAST:event_txtBonKeyReleased

    private void txtBayaranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBayaranFocusLost
        // TODO add your handling code here:
        if (txtBayaran.getText().equals("")){
            txtBayaran.setText("0");    
        }
        
    }//GEN-LAST:event_txtBayaranFocusLost

    private void txtKoordinasiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKoordinasiFocusLost
        // TODO add your handling code here:
        if (txtKoordinasi.getText().equals("")){
        txtKoordinasi.setText("0");
        }
    }//GEN-LAST:event_txtKoordinasiFocusLost

    private void txtPotonganKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPotonganKeyReleased
        // TODO add your handling code here:
        upah();
    }//GEN-LAST:event_txtPotonganKeyReleased

    private void txtSubsidiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSubsidiFocusLost
        // TODO add your handling code here:
        if (txtSubsidi.getText().equals("")){
        txtSubsidi.setText("0");
        }
    }//GEN-LAST:event_txtSubsidiFocusLost

    private void txtBonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBonFocusLost
        // TODO add your handling code here:
        if (txtBon.getText().equals("")){
        txtBon.setText("0");
        }
    }//GEN-LAST:event_txtBonFocusLost

    private void txtPotonganFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPotonganFocusLost
        // TODO add your handling code here:
        if (txtPotongan.getText().equals("")){
        txtPotongan.setText("0");
        }
    }//GEN-LAST:event_txtPotonganFocusLost

    private void txtNoteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNoteFocusLost
        // TODO add your handling code here:
        if (txtNote.getText().equals("")){
        txtNote.setText("Note");
        }
    }//GEN-LAST:event_txtNoteFocusLost

    private void cmbIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIDActionPerformed
        getSupir();
    }//GEN-LAST:event_cmbIDActionPerformed

    private void kdUpah() {
        try {
            String sql = "select * from tb_upah_supir order by kd_upah desc";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet rs=stm.executeQuery(sql);
            if (rs.next()) {
                String kd = rs.getString("kd_upah").substring(1);
                String AN = "" + (Integer.parseInt(kd) + 1);
                txtKdUpah.setText("U" + AN);
            } else {
               txtKdUpah.setText("U1");
            }

           }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
    }
    
    private void cmbID() {
        try { 
            String sql = "select id_supir from tb_supir";
            java.sql.Connection conn=Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                cmbID.addItem(res.getString("id_supir"));
            }
        }catch (Exception e) {
            
        }
        
    }
    
    private void cmbMobil() {
        try { 
            String sql = "select * from tb_mobil";
            java.sql.Connection conn=Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                cmbMobil.addItem(res.getString("kd_mobil"));   
            }
        }catch (Exception e) {
            
        }
        
    }
    
    private void getSupir(){
        try {
            String sql = "SELECT * FROM tb_supir WHERE id_supir = '"+cmbID.getSelectedItem()+"'";
            java.sql.Connection conn=Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            if(res.next() == true) {
                txtNama.setText(res.getString("nm_supir"));
            }
        }catch ( SQLException err ) {
            System.out.println(err.getMessage());
        }   
    }
    
    private void getMobil(){
        try {
            String sql = "SELECT * FROM tb_mobil WHERE kd_mobil = '"+cmbMobil.getSelectedItem()+"'";
            java.sql.Connection conn=Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            if(res.next() == true) {
                txtNopol.setText(res.getString("nopol"));
            }
        }catch ( SQLException err ) {
            System.out.println(err.getMessage());
        }   
    }
    
    private void total() {
        int bayaran = Integer.parseInt(txtBayaran.getText());
        int koordinasi = Integer.parseInt(txtKoordinasi.getText());
        int subsidi = Integer.parseInt(txtSubsidi.getText());
        int bon = Integer.parseInt(txtBon.getText());
        int total = bayaran + koordinasi + subsidi + bon;

        txtTotal.setText(String.valueOf(total));
}
    
    private void upah() {
        int total = Integer.parseInt(txtTotal.getText());
        int potongan = Integer.parseInt(txtPotongan.getText());
        int upah = total - potongan;

        txtUpah.setText(String.valueOf(upah));
    }
    
    private void textboxOn() {
        cmbID.setEnabled(true);
        cmbMobil.setEnabled(true);
        txtBayaran.setEditable(true);
        txtKoordinasi.setEditable(true);
        txtSubsidi.setEditable(true);
        txtBon.setEditable(true);
        txtPotongan.setEditable(true);
        txtNote.setEditable(true);
        jPanel4.setVisible(true);
        btnSimpan.setVisible(true);
        btnBatal.setVisible(true);
        cmbDate.setEnabled(true);
    }
    
    private void textboxOff() {
        txtKdUpah.setEnabled(false);
        cmbID.setEnabled(false);
        txtNama.setEnabled(false);
        cmbMobil.setEnabled(false);
        txtNopol.setEnabled(false);
        txtBayaran.setEditable(false);
        txtKoordinasi.setEditable(false);
        txtSubsidi.setEditable(false);
        txtBon.setEditable(false);
        txtTotal.setEnabled(false);
        txtPotongan.setEditable(false);
        txtUpah.setEnabled(false);
        txtNote.setEditable(false);
        jPanel4.setVisible(false);
        btnSimpan.setVisible(false);
        btnBatal.setVisible(false);
        cmbDate.setEnabled(false);
    }
    
    private void kosong(){
        txtKdUpah.setText("Kode Upah");
        cmbID.setSelectedItem(null);
        txtNama.setText("Nama");
        cmbMobil.setSelectedItem(null);
        txtNopol.setText("NOPOL");
        txtBayaran.setText("0");
        txtKoordinasi.setText("0");
        txtSubsidi.setText("0");
        txtBon.setText("0");
        txtTotal.setText("0");
        txtPotongan.setText("0");
        txtUpah.setText("0");
        txtNote.setText("Note");
        cmbDate.setDate(null);
    }
    private void load_table(){
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Kode Upah");
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Kode Mobil");
        model.addColumn("NOPOL");
        model.addColumn("Bayaran");
        model.addColumn("Kordinasi");
        model.addColumn("Subsidi");
        model.addColumn("Bon");
        model.addColumn("Total");
        model.addColumn("Potongan");
        model.addColumn("Upah");
        model.addColumn("Note");
        model.addColumn("Tanggal");
        
        //menampilkan data database kedalam tabel
        try {
            String sql = "select * from tb_Upah_supir";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8),res.getString(9),res.getString(10),res.getString(11),res.getString(12),res.getString(13),res.getString(14)});
            }
            jTable1.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUpahSupir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUpahSupir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUpahSupir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUpahSupir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUpahSupir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBaru1;
    private javax.swing.JLabel btnBatal;
    private javax.swing.JLabel btnCetak;
    private javax.swing.JLabel btnHapus1;
    private javax.swing.JLabel btnSimpan;
    private com.toedter.calendar.JDateChooser cmbDari;
    private com.toedter.calendar.JDateChooser cmbDate;
    private javax.swing.JComboBox<String> cmbID;
    private javax.swing.JComboBox<String> cmbMobil;
    private com.toedter.calendar.JDateChooser cmbSampai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBayaran;
    private javax.swing.JTextField txtBon;
    private javax.swing.JTextField txtKdUpah;
    private javax.swing.JTextField txtKoordinasi;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNopol;
    private javax.swing.JTextField txtNote;
    private javax.swing.JTextField txtPotongan;
    private javax.swing.JTextField txtSubsidi;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtUpah;
    // End of variables declaration//GEN-END:variables
}
